runtime macros/matchit.vim
syntax on
scriptencoding utf-8
set encoding=utf-8
set nocompatible
set autoread
if has("autocmd")
  filetype indent plugin on
endif

call plug#begin('~/.local/share/nvim/plugged')
Plug '/usr/local/opt/fzf'
Plug 'junegunn/fzf.vim'
Plug 'hrvladev/quill'
Plug 'kchmck/vim-coffee-script'
Plug 'slim-template/vim-slim'
Plug 'janko-m/vim-test'
Plug 'Yggdroot/indentLine'
Plug 'kana/vim-textobj-user'
Plug 'nelstrom/vim-textobj-rubyblock'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rhubarb'
Plug 'tpope/vim-surround'
Plug 'AndrewRadev/writable_search.vim'
Plug 'scrooloose/nerdtree'
Plug 'ap/vim-css-color'
Plug 'easymotion/vim-easymotion'
Plug 'Valloric/YouCompleteMe', { 'do': './install.py' }
Plug 'pangloss/vim-javascript'
Plug 'leafgarland/typescript-vim'
Plug 'maxmellon/vim-jsx-pretty'
Plug 'pangloss/vim-javascript'
Plug 'leafgarland/typescript-vim'
Plug 'maxmellon/vim-jsx-pretty'
Plug 'lmeijvogel/vim-yaml-helper'
Plug 'dense-analysis/ale'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && yarn install'  }
" Plug 'prettier/vim-prettier', { 'do': 'yarn install', 'for': ['javascript', 'typescript', 'css', 'less', 'scss', 'json', 'graphql', 'markdown', 'vue', 'yaml', 'html'] }
call plug#end()

" Mapping
let mapleader      = "\<Space>"
let maplocalleader = "\<Space>"

" Rspec
let test#strategy          = "neovim"
let g:test#preserve_screen = 1

" Indent
" let g:indentLine_showFirstIndentLevel = 1
let g:indentLine_char = '│'
let g:indentLine_first_char = '│'

" Escaping
inoremap jk <Esc>
cnoremap jk <C-c>

" Keys for normal mode
nnoremap <silent> <leader>q :q<CR>
nnoremap <silent> <leader>s :update<CR>
nnoremap <silent> <leader>t :GFiles<CR>
nnoremap <silent> <leader>g :Files<CR>
nnoremap <silent> <leader>b :Buffers<CR>
nnoremap <silent> <leader>l :NERDTreeFind<CR>
nnoremap <silent> t<C-t> :TestNearest<CR>
nnoremap <silent> t<C-f> :TestFile<CR>
nnoremap <silent> t<C-l> :TestLast<CR>
nnoremap <silent> t<C-v> :TestVisit<CR>
nnoremap <Leader>c :nohlsearch<CR>
nnoremap <C-k> :m-2<CR>
nnoremap <C-j> :m+1<CR>
nnoremap <C-n> :tabNext<CR>

" Keys for visual mode
vnoremap <Leader>f y:Ag\V<C-r>=escape(@",'/\')<CR><CR>

set splitright
set splitbelow
set termguicolors
set tabstop=2
set softtabstop=0
set shiftwidth=2
set expandtab
set smarttab
set number

" Remove trailing spaces on save (oh yeah)
autocmd BufWritePre * :%s/\s\+$//e

" Threat jst like html
au BufNewFile,BufRead *.ejs set filetype=html

" highlight tabs and trailing spaces
set listchars=tab:\|\
set list

" highlights
set cursorline

colorscheme quill
highlight Pmenu ctermfg=2 ctermbg=3 guifg=#ffffff guibg=#323742
let g:prettier#autoformat = 0
" autocmd BufWritePre *.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.less,*.scss,*.json,*.graphql,*.md,*.vue,*.yaml,*.html PrettierAsync

let g:fzf_layout = { 'down': '~40%' }

" Ale
" Ale
let g:ale_linters = {
\ "ruby": ["rubocop", "ruby"]
\}
let g:ale_fixers = {
\ "ruby": ["rubocop"]
\}

" Include the Swamp (ALE copies the file to /tmp, so lib::relative stops working ;/)
let g:ale_sign_error = "✘"
let g:ale_sign_warning = "●"
let g:ale_sign_info = "■"
let g:ale_sign_style_error = "✘"
let g:ale_sign_style_warning = "►"

let g:ale_lint_on_text_changed = 0
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_filetype_changed = 1

let g:ale_set_balloons = 1

let g:ale_ruby_rubocop_executable = 'bundle'
highlight clear SignColumn
let g:airline_theme='onedark'

" fold experiments
set foldmethod=indent
set foldnestmax=10
set nofoldenable
set foldlevel=2

" spell check
autocmd BufRead,BufNewFile *.md setlocal spell
autocmd FileType gitcommit setlocal spell

