export ZSH=$HOME/.oh-my-zsh

#theme
ZSH_THEME="clean"

#plugins
plugins=(git ruby rails)

#path
export EDITOR="atom"
export HOMEBREW_GITHUB_API_TOKEN="da4ef96070947e95fc065e94b90d0b460797fee4"

#oh-my-zsh
source $ZSH/oh-my-zsh.sh
source ~/.bin/tmuxinator.zsh

# aliases
alias gm="git fetch && git rebase origin/master"
alias gg="git status"
alias personal="cd ~/Projects/Personal/web"
alias work="cd ~/Projects/Work"
alias rb="cd ~/Projects/Work/receipt-bank/application"
alias reva="cd ~/Projects/Work/receipt-bank/reviewer-app"
alias footy="cd ~/Projects/Appsbakery/footyaddicts"
alias dotfiles="cd ~/Projects/knowledge"
alias gmb="git fetch && git rebase $1"

# Allow [ or ] whereever you want
unsetopt nomatch

#rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
export EDITOR="atom"
export PATH="/usr/local/sbin:/Applications/Postgres.app/Contents/Versions/latest/bin:$PATH"
